StartupPathType: RestorePrevious
DefaultPath: Drives
PreviousPath: Drives
PathFormatName: Windows
ShowHidden: false
TextEditor: notepad.exe
CommandlinePath: cmd.exe
YankRegisterAction: ""
YankRegisterPath: ""
Window:
    IsMaximized: false
    Left: 200
    Top: 200
    Width: 800
    Height: 800
    ShowFullPathInTitle: false
    RefreshOnActivate: true
Bookmarks:
    - Key: _w
      Path: C:\Windows