StartupPathType: RestorePrevious
DefaultPath: Drives
PreviousPath: Drives
PathFormatName: Windows
Window:
    IsMaximized: false
    Left: 200
    Top: 200
    Width: 800
    Height: 800
    ShowFullPathInTitle: false